# build stage
FROM golang:1.18-buster AS build

# Set the working directory for Go
WORKDIR /go/src/${owner:-github.com/IzakMarais}/reporter

# Install dependencies for building the Go application
RUN apt-get update && apt-get install -y make git

# Clone the repository and build the application
RUN git clone https://github.com/IzakMarais/reporter.git .
RUN go install github.com/IzakMarais/reporter/cmd/grafana-reporter@latest

# create image
FROM debian:buster

# Install necessary dependencies and set up TeX Live
RUN PACKAGES="wget libswitch-perl texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra ca-certificates" \
    && apt-get update \
    && apt-get install -y -qq $PACKAGES --no-install-recommends \
    && wget -qO- http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz | tar xz \
    && cd install-tl-* \
    && ./install-tl -profile /texlive.profile \
    # Cleanup
    && rm -rf install-tl-* \
    && apt-get remove --purge -y -qq $PACKAGES \
    && apt-get autoremove --purge -y -qq \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir /var/tex

# Copy the Go binary from the build stage
COPY --from=build /go/bin/grafana-reporter /usr/local/bin

# Define the entrypoint
ENTRYPOINT ["/usr/local/bin/grafana-reporter", "-ip", "jmeter-grafana:3000"]

