apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-slaves
  labels:
    jmeter_mode: slave
spec:
  replicas: 2  # Number of slave replicas
  selector:
    matchLabels:
      jmeter_mode: slave
  template:
    metadata:
      labels:
        jmeter_mode: slave
    spec:
      containers:
        - name: jmslave
          image: afabica234/jmeter-slave:v8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1099   # RMI port for JMeter Master-Slave communication
            - containerPort: 50000  # JMeter's default port for distributed testing
          env:
            - name: JMETER_MASTER_HOST
              value: "jmeter-master"  # This is the name of the service that the JMeter master is exposed under (see below)
          command: ["/bin/bash", "-c", "--"]
          args:
            - |
              echo "Waiting for the master..."
              while ! nc -z jmeter-master 1099; do
                sleep 1
              done
              echo "Connected to the master. Starting JMeter slave..."
              jmeter-server

