apiVersion: v1
kind: Service
metadata:
  name: jmeter-slaves
spec:
  selector:
    jmeter_mode: slave
  ports:
    - name: jmeter-port
      port: 50000
      targetPort: 50000
    - name: rmi-port
      port: 1099
      targetPort: 1099

